### ISSUE TITLE
ComputerChess Wiki

### ISSUE THREAD

**Issue by yellow-panther** [Plan-B6/wowl-chess#2]
Which is your real name for an entry here?
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list

Linux/Windows version >https://drive.google.com/open?id=1zQuoFeGrcOpUrk4mLVOcljC8oq-9bCOA

**Comment by eric-ycw** [comment]
It's Eric Yip, thanks for adding Wowl to the list :)
