### ISSUE TITLE
Illegal bestmove 0000

### ISSUE THREAD

**Issue by tpoppins** [Plan-B6/wowl-chess#4]
Thank you for fixing promotions to a queen; they works as expected now.

Unfortunately, the latest commit seems to have introduced another bug: _bestmove_ is now sometimes returned as 0000.

I use the following position to see how engines handle the KRK endgame:
R7/2K5/8/2k5/8/8/8/8 w - - 0 1

Wowl starts out well but fails to mate. Twice I tried and twice the game game was terminated due to an illegal move (0000), Here's the full debug log for one of them:
[link=https://pastebin.com/ZK6HYGfZ](url)

**Comment by eric-ycw** [comment]
Oh god I made a stupid mistake, thanks for the bug report. It should be fixed now.

**Comment by tpoppins** [comment]
Excellent!

The problem appears to be solved, and now we can see that Wowl can handle the KRK ending reasonably:

```
[Event "?"]
[Site "?"]
[Date "2018.09.23"]
[Round "?"]
[White "Wowl 1.3.6"]
[Black "_SF9"]
[Result "1-0"]
[FEN "R7/2K5/8/2k5/8/8/8/8 w - - 0 1"]
[GameDuration "00:01:04"]
[GameEndTime "2018-09-23T22:19:53.117 Eastern Daylight Time"]
[GameStartTime "2018-09-23T22:18:49.002 Eastern Daylight Time"]
[PlyCount "33"]
[SetUp "1"]
[TimeControl "40/120"]

1. Rd8 {+7.99/15 2.9s} Kb5 {-M22/52 2.0s} 2. Rd7 {+8.16/17 2.9s}
Kc5 {-M22/50 1.0s} 3. Rd6 {+8.16/18 2.9s} Kb4 {-M20/56 1.1s}
4. Kb7 {+8.16/15 2.9s} Kc5 {-M22/56 2.2s} 5. Rd8 {+8.75/18 2.9s}
Kb5 {-M20/58 0.81s} 6. Rc8 {+842.25/17 2.9s} Ka5 {-M18/69 2.7s}
7. Kc6 {+880.61/16 2.9s} Kb4 {-M16/68 0.85s} 8. Kb6 {+833.65/19 2.9s}
Ka3 {-M14/78 1.2s} 9. Kb5 {+833.67/21 2.9s} Kb3 {-M12/103 1.2s}
10. Rc6 {+833.69/22 2.9s} Ka3 {-M10/127 0.49s} 11. Rc2 {+833.69/23 3.0s}
Kb3 {-132.79/1 0s} 12. Rc6 {+833.69/22 2.9s} Ka2 {-M10/127 0.42s}
13. Kb4 {+833.69/24 3.0s} Kb2 {-M8/127 0.015s} 14. Rc8 {+833.70/23 3.0s}
Ka2 {-M6/127 0.012s} 15. Kc3 {+833.70/22 3.0s} Ka1 {-M4/127 0.004s}
16. Kc2 {+833.72/22 3.0s} Ka2 {-M2/1 0s} 17. Ra8# {+833.74/23 3.0s, White mates}
1-0
```
