### ISSUE TITLE
Promotion to queen for Black is broken

### ISSUE THREAD

**Issue by tpoppins** [Plan-B6/wowl-chess#5]
When playing Black Wowl omits the **q** suffix from the move when promoting to a queen. That affects both _the PV_ and _bestmove_.

Sorry for missing that initially; the EPD I've been using to test whether engines promote correctly tested only White. Now thanks to Wowl I have the following FEN from one of its games vs. Wuttang (which played White):
8/1P3k2/8/4Kn2/R7/P7/6p1/8 b - - 0 62

In this position White and Black both have a pawn about to promote.

Currently, this is  Wowl 1.3.6's output for this position:
```
<Wowl 1.3.6(341): info score cp -356 depth 15 nodes 579948 time 31400 pv g2g1 b7b8q g1c5 e5f4 f5e7 b8b3 f7g7 f4f3 c5f5 f3g2 f5f2 g2h3 f2f1 h3h4 f1f2 
<Wowl 1.3.6(341): move ordering 68.5
<Wowl 1.3.6(341): bestmove g2g1 
```

**Comment by eric-ycw** [comment]
Thanks again! Your testing has uncovered a lot of issues that I didn't catch. The problem should be fixed now.
